using ExitGames.Client.Photon;
using ITCompanySimulation.Character;
using ITCompanySimulation.Developing;
using ITCompanySimulation.Multiplayer;
using System.Collections;
using UnityEngine;
using UnityEngine.Events;
using UnityEngine.SceneManagement;

namespace ITCompanySimulation.Core
{
    /// <summary>
    /// This class handles main game aspects like loading scenes, transf and
    /// handling multiplayer connection
    /// </summary>
    public class MainGameManager : Photon.PunBehaviour
    {
        /*Private consts fields*/

        private const string GAME_VERSION = "1.0";
        /// <summary>
        /// How many reconnect should be made when cannot connect to server
        /// or after being disconnected from server
        /// </summary>
        private const int MAX_RECONNECT_RETRIES = 5;

        /*Private fields*/

        private bool MenuSceneLoadedAfterGameFinish;
        /// <summary>
        /// How many clients can receive data generated by master client.
        /// Each of clients will send notification to master client when
        /// he is ready to receive data
        /// </summary>
        private int NumberOfClientsReadyToReceiveData;

        /// <summary>
        /// Below values can be used to set balance when game creation through room is not used
        /// </summary>
        [SerializeField]
        private int InitialCompanyBalance;
        [SerializeField]
        private int TargetCompanyBalance;
        [SerializeField]
        private int MinimalCompanyBalance;

        /// <summary>
        /// When this is set to true simulation will be run in
        /// Offline Mode. It means that this client won't be connected
        /// to server and simulation will be run in local environment.
        /// This will allow to run some of game mechanism like generation
        /// of projects and workers without actually connecting to server.
        /// Value of this variable will be also set in PhotonNetwork.offlineMode
        /// https://doc.photonengine.com/en-us/pun/current/gameplay/offlinemode
        /// </summary>
        [SerializeField]
        private bool OfflineMode;
        private int ReconnectRetries = 0;

        /*Public consts fields*/

        public const int MAX_NUMBER_OF_PLAYERS_PER_ROOM = 4;
        public const int MIN_NUMBER_OF_PLAYERS_PER_ROOM = 2;

        /*Public fields*/

        /// <summary>
        /// If set to true before game starts user will have to create room and
        /// define simulation settings. If false game will start without need to create
        /// room and default room and simulation settings will be set
        /// </summary>
        public bool UseRoom;
        public event UnityAction ReconnectFailed;

        /*Private methods*/

        private void Awake()
        {
            //TODO: Register all types inside this method
            //Register custom classes that will be sent between clients
            PhotonPeer.RegisterType(typeof(SharedProject), NetworkingData.PROJECT_BYTE_CODE, SharedProject.Serialize, SharedProject.Deserialize);
            //Needed to register both base and derived class of worker because photon API requires
            //derived class to be register event when using base class argument in method
            PhotonPeer.RegisterType(typeof(LocalWorker), NetworkingData.LOCAL_WORKER_BYTE_CODE, SharedWorker.Serialize, SharedWorker.Deserialize);
            PhotonPeer.RegisterType(typeof(SharedWorker), NetworkingData.SHARED_WORKER_BYTE_CODE, SharedWorker.Serialize, SharedWorker.Deserialize);

            DontDestroyOnLoad(this.gameObject);
            PhotonNetwork.offlineMode = this.OfflineMode;
            this.photonView.viewID = 1;
            PlayerInfo.Load();

            if (false == PhotonNetwork.offlineMode)
            {
                PhotonNetwork.ConnectUsingSettings(GAME_VERSION);
            }

            PhotonNetwork.OnEventCall += PhotonNetworkOnEventCall;
            SceneManager.sceneLoaded += OnSceneLoaded;
        }

        private void OnSceneLoaded(Scene loadedScene, LoadSceneMode sceneLoadMode)
        {
            NumberOfClientsReadyToReceiveData = 0;

            if ((int)SceneIndex.Game == loadedScene.buildIndex)
            {
                if (false == PhotonNetwork.isMasterClient)
                {

                    RaiseEventOptions options = new RaiseEventOptions
                    {
                        Receivers = ReceiverGroup.Others
                    };

                    PhotonNetwork.RaiseEvent((byte)RaiseEventCode.ClientReadyToReceiveData, null, true, options);
                }
            }
        }

        private void PhotonNetworkOnEventCall(byte eventCode, object content, int senderId)
        {
            switch (eventCode)
            {
                case (byte)RaiseEventCode.ClientReadyToReceiveData:
                    if (true == PhotonNetwork.isMasterClient)
                    {
                        ++NumberOfClientsReadyToReceiveData;

                        //All other players are ready to receive data, time to start game for master client
                        if (NumberOfClientsReadyToReceiveData == PhotonNetwork.playerList.Length - 1)
                        {
                            StartGameInternal();
                        }
                    }
                    break;
                default:
                    break;
            }
        }

        [PunRPC]
        private void StartGameInternal()
        {
            SceneManager.LoadScene((int)SceneIndex.Game);
        }

        private IEnumerator ReconnectCoroutine()
        {
            yield return new WaitForSecondsRealtime(5.0f);
            PhotonNetwork.ConnectUsingSettings(GAME_VERSION);
            ++ReconnectRetries;
        }

        /*Public methods*/

        public void StartGame()
        {
            if (false == UseRoom)
            {
                //Create room with default settings and join it
                SimulationSettings.InitialBalance = this.InitialCompanyBalance;
                SimulationSettings.TargetBalance = this.TargetCompanyBalance;
                SimulationSettings.MinimalBalance = this.MinimalCompanyBalance;
                RoomOptions options = new RoomOptions() { MaxPlayers = MAX_NUMBER_OF_PLAYERS_PER_ROOM };
                PhotonNetwork.JoinOrCreateRoom("Default", options, PhotonNetwork.lobby);
            }

            //Master client will wait for other clients until they are ready to receive data
            //then start game
            if (true == PhotonNetwork.isMasterClient)
            {
                PhotonNetwork.room.IsOpen = false;
                //In offline mode game will be started immediately
                PhotonTargets targets = PhotonNetwork.offlineMode ? PhotonTargets.All : PhotonTargets.Others;
                this.photonView.RPC("StartGameInternal", targets);
            }
        }

        public void FinishSession()
        {
            PhotonNetwork.LeaveRoom();
            SceneManager.LoadScene((int)SceneIndex.Menu);
        }

        public void Connect()
        {
            ReconnectRetries = 0;
            PhotonNetwork.ConnectUsingSettings(GAME_VERSION);
        }

        public override void OnConnectedToMaster()
        {
            base.OnConnectedToMaster();

            ReconnectRetries = 0;
#if DEVELOPMENT_BUILD || UNITY_EDITOR
            string msg = string.Format("[{0}] Connected to master", this.GetType().Name);
            Debug.Log(msg);
#endif
        }

        /// <summary>
        /// Is called when client is connected to photon since auto
        /// join lobby is set to true
        /// </summary>
        public override void OnJoinedLobby()
        {
            base.OnJoinedLobby();

#if DEVELOPMENT_BUILD || UNITY_EDITOR
            string msg = string.Format("[{0}] Joined lobby: {1}",
                                       this.GetType().Name,
                                       PhotonNetwork.lobby.Name);
            Debug.Log(msg);
#endif
        }

        public override void OnJoinedRoom()
        {
            base.OnJoinedRoom();

            //Game will be started in online mode but only with one player in room
            if (false == UseRoom)
            {
                StartGameInternal();
            }

#if DEVELOPMENT_BUILD || UNITY_EDITOR
            string msg = string.Format("[{0}] Joined room\n" +
                               "Name: {1}\n" +
                               "Number of players: {2}\n" +
                               "Max number of players : {3}" +
                               "Open: {4}",
                               this.GetType().Name,
                               PhotonNetwork.room.Name,
                               PhotonNetwork.room.PlayerCount,
                               PhotonNetwork.room.MaxPlayers,
                               PhotonNetwork.room.IsOpen);
            Debug.Log(msg);
#endif
        }

        public override void OnDisconnectedFromPhoton()
        {
            base.OnDisconnectedFromPhoton();

            if (MAX_RECONNECT_RETRIES != ReconnectRetries)
            {
                StartCoroutine(ReconnectCoroutine());
            }
            else
            {
                ReconnectFailed?.Invoke();
            }

#if DEVELOPMENT_BUILD || UNITY_EDITOR
            string msg = string.Format("[{0}] Disconnected from Photon", this.GetType().Name);
            Debug.Log(msg);
#endif
        }

        public override void OnConnectionFail(DisconnectCause cause)
        {
            base.OnConnectionFail(cause);

#if DEVELOPMENT_BUILD || UNITY_EDITOR
            string msg = string.Format("[{0}] Connection failed. Reason: {1}",
                                       this.GetType().Name,
                                       cause);
            Debug.Log(msg);
#endif
        }

        public override void OnPhotonJoinRoomFailed(object[] codeAndMsg)
        {
            base.OnPhotonJoinRoomFailed(codeAndMsg);

#if DEVELOPMENT_BUILD || UNITY_EDITOR
            string msg = string.Format("[{0}] Failed to join the room", this.GetType().Name);
            Debug.Log(msg);
#endif
        }
    }
}
