using ExitGames.Client.Photon;
using ITCompanySimulation.Character;
using ITCompanySimulation.Developing;
using ITCompanySimulation.Multiplayer;
using ITCompanySimulation.Utilities;
using System.Collections;
using UnityEngine;
using UnityEngine.Events;
using UnityEngine.SceneManagement;
using System.Linq;
using System;

#if DEVELOPMENT_BUILD || UNITY_EDITOR
using System.Reflection;
#endif

namespace ITCompanySimulation.Core
{
    /// <summary>
    /// This class handles main game aspects like loading scenes, transfer,
    /// handling multiplayer connection and multiplayer session
    /// </summary>
    public class MainGameManager : Photon.PunBehaviour
    {
        /*Private consts fields*/

        private const string GAME_VERSION = "1.0";
        /// <summary>
        /// How many reconnect should be made when cannot connect to server
        /// or after being disconnected from server
        /// </summary>
        private const int MAX_RECONNECT_RETRIES = 5;

        /*Private fields*/

        private bool MenuSceneLoadedAfterGameFinish;
        /// <summary>
        /// How many clients can receive data generated by master client.
        /// Each of clients will send notification to master client when
        /// he is ready to receive data
        /// </summary>
        private int NumberOfClientsReadyToReceiveData;
        /// <summary>
        /// Each of clients will send notification to master client when
        /// he received all data
        /// </summary>
        private int NumberOfClientsWithDataReceived;
        /// <summary>
        /// Number of this client's data transfers required by components to start simulation
        /// </summary>
        private int NumberOfCompletedDataTransfers;
        /// <summary>
        /// Components that need to receive data before starting session
        /// </summary>
        private IDataReceiver[] DataReceiverComponents;
        /// <summary>
        /// Below values can be used to set balance when game creation through room is not used
        /// </summary>
        [SerializeField]
        private int InitialCompanyBalance;
        [SerializeField]
        private int TargetCompanyBalance;
        [SerializeField]
        private int MinimalCompanyBalance;
        /// <summary>
        /// When this is set to true simulation will be run in
        /// Offline Mode. It means that this client won't be connected
        /// to server and simulation will be run in local environment.
        /// This will allow to run some of game mechanism like generation
        /// of projects and workers without actually connecting to server.
        /// Value of this variable will be also set in PhotonNetwork.offlineMode
        /// https://doc.photonengine.com/en-us/pun/current/gameplay/offlinemode
        /// </summary>
        [SerializeField]
        private bool OfflineMode;
        private int ReconnectRetries = 0;

        /*Public consts fields*/

        public const int MAX_NUMBER_OF_PLAYERS_PER_ROOM = 4;
        public const int MIN_NUMBER_OF_PLAYERS_PER_ROOM = 2;

        /*Public fields*/

        /// <summary>
        /// If set to true before game starts user will have to create room and
        /// define simulation settings. If false game will start without need to create
        /// room and default room and simulation settings will be set
        /// </summary>
        public bool UseRoom;
        /// <summary>
        /// True when session has started and is active
        /// </summary>
        public bool IsSessionActive { get; private set; }
        public event UnityAction ReconnectFailed;
        public event UnityAction SessionStarted;

        /*Private methods*/

        private void Awake()
        {
            //Register custom classes that will be sent between clients
            PhotonPeer.RegisterType(typeof(SharedProject), NetworkingData.PROJECT_BYTE_CODE, SharedProject.Serialize, SharedProject.Deserialize);
            //Needed to register both base and derived class of worker because photon API requires
            //derived class to be register event when using base class argument in method
            PhotonPeer.RegisterType(typeof(LocalWorker), NetworkingData.LOCAL_WORKER_BYTE_CODE, SharedWorker.Serialize, SharedWorker.Deserialize);
            PhotonPeer.RegisterType(typeof(SharedWorker), NetworkingData.SHARED_WORKER_BYTE_CODE, SharedWorker.Serialize, SharedWorker.Deserialize);

            DontDestroyOnLoad(this.gameObject);
            PhotonNetwork.offlineMode = this.OfflineMode;
            this.photonView.viewID = 1;
            PlayerInfo.Load();
            //In PUN Classic, if the client does not set a UserId,
            //the UserId will be set to the Nickname before connecting. In PUN2 this is no longer the case.
            string userID = Guid.NewGuid().ToString();
            PhotonNetwork.AuthValues = new AuthenticationValues(userID);

            if (false == PhotonNetwork.offlineMode)
            {
                PhotonNetwork.ConnectUsingSettings(GAME_VERSION);
            }

            PhotonNetwork.OnEventCall += PhotonNetworkOnEventCall;
            SceneManager.sceneLoaded += OnSceneLoaded;
        }

        private void OnSceneLoaded(Scene loadedScene, LoadSceneMode sceneLoadMode)
        {
            if ((int)SceneIndex.Game == loadedScene.buildIndex)
            {
                SessionStarted = null;
                NumberOfClientsReadyToReceiveData = 0;
                NumberOfClientsWithDataReceived = 0;
                NumberOfCompletedDataTransfers = 0;

                if (false == PhotonNetwork.offlineMode && true == UseRoom)
                {
                    DataReceiverComponents = GameObject.FindObjectsOfType<MonoBehaviour>().OfType<IDataReceiver>().ToArray();

                    foreach (IDataReceiver receiver in DataReceiverComponents)
                    {
                        if (true == receiver.IsDataReceived)
                        {
                            OnComponentDataTransfered();
                        }
                        else
                        {
                            receiver.DataReceived += OnComponentDataTransfered;
                        }
                    }

                    if (false == PhotonNetwork.isMasterClient)
                    {
                        RaiseEventOptions options = new RaiseEventOptions
                        {
                            Receivers = ReceiverGroup.Others
                        };

                        PhotonNetwork.RaiseEvent((byte)RaiseEventCode.ClientReadyToReceiveData, null, true, options);
                    }
                }
                else
                {
                    //No need to receive data in offline mode
                    StartSessionRPC();
                }
            }
        }

        private void PhotonNetworkOnEventCall(byte eventCode, object content, int senderId)
        {
            switch (eventCode)
            {
                case (byte)RaiseEventCode.ClientReadyToReceiveData:
                    ++NumberOfClientsReadyToReceiveData;

                    if (true == PhotonNetwork.isMasterClient)
                    {
                        //All other players are ready to receive data, time to start game for master client
                        if (NumberOfClientsReadyToReceiveData == PhotonNetwork.playerList.Length - 1)
                        {
                            StartGameInternal();
                        }
                    }
                    break;
                case (byte)RaiseEventCode.ClientReceivedData:
                    ++NumberOfClientsWithDataReceived;

                    if (true == PhotonNetwork.isMasterClient)
                    {
                        if (NumberOfClientsWithDataReceived == PhotonNetwork.otherPlayers.Length)
                        {
#if DEVELOPMENT_BUILD || UNITY_EDITOR
                            Debug.LogFormat("[{0}] All clients ({1}) received data. Starting sesssion",
                                this.GetType().Name, PhotonNetwork.otherPlayers.Length);
#endif
                            photonView.RPC("StartSessionRPC", PhotonTargets.All);
                        }
                    }
                    break;
                default:
                    break;
            }
        }

        [PunRPC]
        private void StartGameInternal()
        {
            LoadScene((int)SceneIndex.Game);
        }

        [PunRPC]
        private void StartSessionRPC()
        {
#if DEVELOPMENT_BUILD || UNITY_EDITOR
            Debug.LogFormat("[{0}] {1} called. Starting session...",
                this.GetType().Name,
                MethodBase.GetCurrentMethod().Name);
#endif
            StartCoroutine(StartSessionCoroutine());
        }

        private IEnumerator StartSessionCoroutine()
        {
            //Wait one frame so components that want to subcribe to
            //SessionStarted event can be initialized after game scene
            //being loaded
            yield return null;

            IsSessionActive = true;
            //Session has started now, notify other components
            SessionStarted?.Invoke();
        }

        private IEnumerator ReconnectCoroutine()
        {
            yield return new WaitForSecondsRealtime(5.0f);
            PhotonNetwork.ConnectUsingSettings(GAME_VERSION);
            ++ReconnectRetries;
        }

        private void OnComponentDataTransfered()
        {
            ++NumberOfCompletedDataTransfers;

            if (DataReceiverComponents.Length == NumberOfCompletedDataTransfers)
            {
                if (false == PhotonNetwork.isMasterClient)
                {
#if DEVELOPMENT_BUILD || UNITY_EDITOR
                    Debug.LogFormat("[{0}] All components received data. Notifying master client",
                        this.GetType().Name);
#endif
                    //Notify master client that all required data is received
                    RaiseEventOptions options = new RaiseEventOptions
                    {
                        Receivers = ReceiverGroup.Others
                    };

                    PhotonNetwork.RaiseEvent((byte)RaiseEventCode.ClientReceivedData, null, true, options);
                }
            }
        }

        /*Public methods*/

        public void StartGame()
        {
            if (false == UseRoom)
            {
                //Create room with default settings and join it
                SimulationSettings.InitialBalance = this.InitialCompanyBalance;
                SimulationSettings.TargetBalance = this.TargetCompanyBalance;
                SimulationSettings.MinimalBalance = this.MinimalCompanyBalance;
                RoomOptions options = new RoomOptions() { MaxPlayers = MAX_NUMBER_OF_PLAYERS_PER_ROOM };
                PhotonNetwork.JoinOrCreateRoom("Default", options, PhotonNetwork.lobby);
            }

            //Master client will wait for other clients until they are ready to receive data
            //then start game
            if (true == PhotonNetwork.isMasterClient)
            {
                PhotonNetwork.room.IsOpen = false;
                //In offline mode game will be started immediately
                PhotonTargets targets = PhotonNetwork.offlineMode ? PhotonTargets.All : PhotonTargets.Others;
                this.photonView.RPC("StartGameInternal", targets);
            }
        }

        public void FinishSession()
        {
            IsSessionActive = false;
            PhotonNetwork.LeaveRoom();
        }

        public void Connect()
        {
            ReconnectRetries = 0;
            PhotonNetwork.ConnectUsingSettings(GAME_VERSION);
        }

        public void LoadScene(int sceneIndex)
        {
            if (SceneManager.GetActiveScene().buildIndex != sceneIndex)
            {
                SceneManager.LoadScene(sceneIndex);
            }
        }

        public override void OnConnectedToMaster()
        {
            base.OnConnectedToMaster();

            ReconnectRetries = 0;
#if DEVELOPMENT_BUILD || UNITY_EDITOR
            string msg = string.Format("[{0}] Connected to master", this.GetType().Name);
            Debug.Log(msg);
#endif
        }

        /// <summary>
        /// Is called when client is connected to photon since auto
        /// join lobby is set to true
        /// </summary>
        public override void OnJoinedLobby()
        {
            base.OnJoinedLobby();

#if DEVELOPMENT_BUILD || UNITY_EDITOR
            string msg = string.Format("[{0}] Joined lobby: {1}",
                                       this.GetType().Name,
                                       PhotonNetwork.lobby.Name);
            Debug.Log(msg);
#endif
        }

        public override void OnJoinedRoom()
        {
            base.OnJoinedRoom();

            //Game will be started in online mode but only with one player in room
            if (false == UseRoom && false == PhotonNetwork.offlineMode)
            {
                StartGameInternal();
            }

#if DEVELOPMENT_BUILD || UNITY_EDITOR
            string msg = string.Format("[{0}] Joined room\n" +
                               "Name: {1}\n" +
                               "Number of players: {2}\n" +
                               "Max number of players : {3}" +
                               "Open: {4}",
                               this.GetType().Name,
                               PhotonNetwork.room.Name,
                               PhotonNetwork.room.PlayerCount,
                               PhotonNetwork.room.MaxPlayers,
                               PhotonNetwork.room.IsOpen);
            Debug.Log(msg);
#endif
        }

        public override void OnDisconnectedFromPhoton()
        {
            base.OnDisconnectedFromPhoton();

            if (MAX_RECONNECT_RETRIES != ReconnectRetries)
            {
                StartCoroutine(ReconnectCoroutine());
            }
            else
            {
                ReconnectFailed?.Invoke();
            }

#if DEVELOPMENT_BUILD || UNITY_EDITOR
            string msg = string.Format("[{0}] Disconnected from Photon", this.GetType().Name);
            Debug.Log(msg);
#endif
        }

        public override void OnConnectionFail(DisconnectCause cause)
        {
            base.OnConnectionFail(cause);

#if DEVELOPMENT_BUILD || UNITY_EDITOR
            string msg = string.Format("[{0}] Connection failed. Reason: {1}",
                                       this.GetType().Name,
                                       cause);
            Debug.Log(msg);
#endif
        }

        public override void OnPhotonJoinRoomFailed(object[] codeAndMsg)
        {
            base.OnPhotonJoinRoomFailed(codeAndMsg);

#if DEVELOPMENT_BUILD || UNITY_EDITOR
            string msg = string.Format("[{0}] Failed to join the room", this.GetType().Name);
            Debug.Log(msg);
#endif
        }
    }
}
